version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: spoonity_meetings
      POSTGRES_USER: spoonity_user
      POSTGRES_PASSWORD: spoonity_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
